version: '3.3'
services:
  server:
    image: docker-swarm-networks-server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8080:8080
    command: ["server"]
    deploy:
      replicas: 2
  client:
    image: docker-swarm-networks-client
    build:
      context: .
      dockerfile: Dockerfile.client
    command: ["client"]
    deploy:
      replicas: 2
